#!/bin/sh

T= exec

tclsh()
{
	$T /tools/2000/tcl/bin/tclsh8.5 "$@"
}
type tclsh
echo 'puts [set tcl_version]' | tclsh
T="strace -f"
echo load tcl_parser_library.so Parser_library | tclsh 2>f1 
T="strace -f" 
tclsh why_fail.tcl 2>f2
