#!/bin/bash

# obviously this does not work
# surprisingly it is clonezillas fault
# it gets from the iso to the boot pxe menu
# but the initrd is opaque an needs init=cmd line
#
# Initramfs unpacking failed: write error

. ./.env
# see # . boot_fn_WITH_OPT

# boot_zilla # VM += BOOT_iso as DVD=VM.dvd

# OPTS="$OPTS -fda fat:floppy:DIR1"

#	OPTS="$OPTS -snapshot"

# WITH_OPT hda # -snapshot early
#  WITH_OPT hda_sdb # SD_dev_sdb == USB # RW

if false
then
# put these 2 together
# run freedos
# get A>
# B:
# DIR
# type in_DIR1.txt
  WITH_OPT fda_freedos
  WITH_OPT fdb_DIR1 # in_DIR1.txt
fi

  # this is supposed to be all needed
 #WITH_OPT iso

  WITH_OPT hda_sdb # sdb == iso ## prev
  
  # set -x
  ask_do \
  QEMU \
  qemu-system-x86_64 \
  $OPTS

