PATH=$HOME/bin:$PATH
. ~/.bashrc

type GET_GIT

# https://information-cascade.monday.com/

# echo 'git submodule update --init # in tree-sitter/tree-sitter main'
# svn is not git 
# svn://svn.code.sf.net/p/codeblocks/code/trunk

# too many dirs
# git://anongit.freedesktop.org/git/xorg/lib/libXaw3d

L1="
https://github.com/X11Libre/xserver
https://gitlab.gnome.org/GNOME/gjs

https://github.com/GNOME/gnome-keyring
https://gitlab.gnome.org/GNOME/atk.git
https://gitlab.gnome.org/GNOME/gdk-pixbuf.git
https://gitlab.gnome.org/GNOME/glib.git
https://gitlab.gnome.org/GNOME/glib-networking.git
https://gitlab.gnome.org/GNOME/gtk.git
https://gitlab.gnome.org/GNOME/pango.git
https://gitlab.gnome.org/GNOME/pygobject.git
#https://github.com/GNOME/gnome-alsamixer
https://github.com/midi2-dev
https://github.com/midi2-dev/MIDI2.0Workbench
https://github.com/midi2-dev/AM_MIDI2.0Lib
https://github.com/midi2-dev/tusb_ump
https://github.com/midi2-dev/ni-midi2
https://github.com/midi2-dev/bl-midi2-rs
https://github.com/midi2-dev/usbMIDI2DescriptorBuilder
https://github.com/midi2-dev/AmeNote_Protozoa


https://github.com/adaltas/node-csv
https://github.com/vercel/next.js
https://github.com/samizdatco/skia-canvas
https://github.com/frectonz/pglite-fusion
https://github.com/ecere/sdk.git 
https://github.com/oven-sh/bun
https://github.com/Gnucash/gnucash
https://github.com/Gnucash/gnucash-docs
https://github.com/TigerVNC/tigervnc
https://github.com/rfbproto/rfbproto
https://github.com/modularml/mojo
https://github.com/android/platform-samples
https://github.com/WiseLibs/better-sqlite3
https://github.com/ytdl-org/youtube-dl
https://github.com/zed-industries/zed

https://github.com/quilljs/quill
https://github.com/quilljs/parchment
https://github.com/quilljs/delta
https://github.com/quilljs/awesome-quill
https://github.com/biomejs/biome
https://github.com/biomejs/biome-zed
https://github.com/OpenDingux/jzboot
https://github.com/OpenDingux/alsa-volume
https://github.com/OpenDingux/buildroot
https://github.com/OpenDingux/linux

https://github.com/OpenDingux/gmenu2x
https://github.com/OpenDingux/SDL


https://github.com/espressif/book-esp32c3-iot-projects
https://github.com/mihaimoga/IntelliFile
https://github.com/cmajor-lang/cmajor
https://github.com/lvgl/lvgl
https://github.com/ELENA-LANG/elena-lang
https://github.com/espressif/esp-bsp
https://github.com/espressif/esp-usb
https://github.com/espressif/esp-adf
# EGS
https://github.com/davetron5000/ghola
#
https://skia.googlesource.com/skia.git
https://github.com/lvgl/lvgl
#https://github.com/FreeRTOS/FreeRTOS-Kernel
https://github.com/hollance/synth-plugin-book
https://github.com/NationalSecurityAgency/ghidra
https://github.com/nbauers/Learn-x86-assembler
https://github.com/audacity/audacity
https://github.com/audacity/conan-recipes
https://github.com/audacity/audacity-manual
https://github.com/kabouzeid/Phonograph
https://github.com/chr56/Phonograph_Plus
https://github.com/enricocid/Music-Player-GO
https://github.com/googleworkspace/apps-script-samples
https://github.com/googleworkspace/node-samples
https://github.com/googleworkspace/python-samples
https://github.com/googleworkspace/apps-script-oauth2
https://github.com/googleworkspace/android-samples
https://github.com/googleworkspace/md2googleslides

https://github.com/mity/md4c
https://github.com/juce-framework/JUCE
https://github.com/libsndfile/libsndfile
https://github.com/gps67/YEAR_src_PLAY_PREP
https://github.com/mihaimoga/IntelliTask
https://github.com/SimpleMobileTools/Simple-Music-Player
https://github.com/SimpleMobileTools/Simple-Calendar
https://github.com/SimpleMobileTools/Simple-File-Manager
https://github.com/SimpleMobileTools/Simple-Contacts
https://github.com/SimpleMobileTools/Simple-Notes
https://github.com/SimpleMobileTools/Simple-Gallery
https://github.com/SimpleMobileTools/Simple-Commons
https://github.com/SimpleMobileTools/Simple-Dialer
https://github.com/SimpleMobileTools/Simple-Calculator
https://github.com/SimpleMobileTools/Simple-Flashlight
https://github.com/SimpleMobileTools/Simple-Clock
https://github.com/SimpleMobileTools/Simple-Voice-Recorder
https://github.com/SimpleMobileTools/Simple-Thank-You
https://github.com/SimpleMobileTools/Simple-Launcher
https://github.com/SimpleMobileTools/Simple-Keyboard
https://github.com/SimpleMobileTools/Simple-Draw
https://github.com/SimpleMobileTools/Simple-SMS-Messenger
https://github.com/SimpleMobileTools/General-Discussion
https://github.com/SimpleMobileTools/simplemobiletools.github.io

https://github.com/vanilla-music/vanilla
https://github.com/VinylMusicPlayer/VinylMusicPlayer
https://github.com/iampawan/Flutter-Music-Player
https://github.com/naman14/Timber
https://github.com/timusus/Shuttle/
https://github.com/timusus/Shuttle2
https://github.com/naman14/TimberX

https://github.com/nodejs/node
https://github.com/libevent/libevent
https://github.com/Tonejs/Tone.js
https://github.com/Tonejs/ui
https://github.com/libsdl-org/SDL
https://github.com/slint-ui/slint
https://github.com/bellard/quickjs
https://github.com/dbetz/xlisp
https://github.com/danginsburg/opengles-book-samples
https://github.com/danginsburg/opengles3-book/
https://github.com/steelbrain/node-ssh
https://github.com/libuv/libuv
https://github.com/basecamp/trix
https://github.com/swig/swig
https://github.com/v8/v8
https://github.com/mozilla-spidermonkey/spidermonkey.dev
https://github.com/intel/hyperscan
https://github.com/PCRE2Project/pcre2
https://github.com/google/oboe
https://github.com/googlesamples/android-ndk
https://github.com/joaocarvalhoopen/How_to_learn_modern_Rust
https://github.com/libexpat/libexpat
git://git.savannah.nongnu.org/scew.git
https://github.com/academind/aws-demos.git
https://github.com/VCVRack/Rack
https://github.com/VCVRack/library
https://github.com/VCVRack/rack-plugin-toolchain
https://github.com/VCVRack/Fundamental
https://github.com/VCVRack/ESeries
https://github.com/VCVRack/glfw
https://github.com/VCVRack/pichenettes-eurorack
https://github.com/VCVRack/Befaco
https://github.com/VCVRack/AudibleInstruments
https://github.com/VCVRack/rtaudio
https://github.com/microsoft/fluentui-emoji
https://github.com/rg3/youtube-dl
https://github.com/libjpeg-turbo/libjpeg-turbo
https://github.com/pyscript/pyscript
http://sourceware.org/git/binutils-gdb.git
https://github.com/oracle/binutils-gdb
https://github.com/oracle/binutils-gdb/wiki
https://gitlab.freedesktop.org/xorg/lib/libXaw3d
https://github.com/lxc/lxd
https://github.com/pschatzmann/arduino-audio-tools
https://github.com/pschatzmann/ESP32-A2DP
https://github.com/Automattic/node-canvas
https://gitlab.com/cairo/cairo-demos
git@gitlab.com:cairo/cairo-demos.git
git://anongit.freedesktop.org/git/cairo
git://anongit.freedesktop.org/git/pixman.git
https://github.com/karma9874/AndroRAT
https://github.com/kitasuke/monkey-go
https://github.com/derekbanas/Python4Finance
git://git.ghostscript.com/mupdf.git
https://github.com/msteveb/jimtcl.git

https://github.com/http-party/http-server

https://github.com/CreateJS/SoundJS
https://github.com/CreateJS/EaselJS
https://github.com/CreateJS/TweenJS
https://github.com/CreateJS/PreloadJS
https://github.com/CreateJS/Zoe
https://github.com/CreateJS/CreateJS

https://gitlab.freedesktop.org/freetype/freetype-demos
https://gitlab.freedesktop.org/freetype/freetype
https://github.com/NativeScript/NativeScript.git
git://sourceware.org/git/elfutils.git
https://github.com/antirez/linenoise
https://github.com/mozilla-spidermonkey/spidermonkey-embedding-examples
https://github.com/danchitnis/webgl-plot-examples
https://github.com/MrRio/jsPDF
https://github.com/danchitnis/webgl-plot
https://github.com/leeoniya/uPlot
https://github.com/FreeRDP/FreeRDP
git://git.code.sf.net/p/flwm/flwm
https://github.com/fltk/fltk
https://github.com/fltk/nanosvg
https://github.com/Ahiknsr/X11clippy
https://github.com/AssemblyScript/examples
https://github.com/AssemblyScript/assemblyscript
https://github.com/AssemblyScript/website
https://github.com/AssemblyScript/wabt.js
https://github.com/AssemblyScript/binaryen.js
https://github.com/keithclark/ZzFXM
git://code.qt.io/qt/qt5.git
https://github.com/mozilla-lockwise/lockwise-addon
https://github.com/mozilla-lockwise/lockwise-android
https://github.com/mozilla-lockwise/lockbox-demo
https://github.com/mozilla-lockwise/assets
https://github.com/mozilla-lockwise/mozilla-lockwise.github.io
https://github.com/libssh2/libssh2.git
https://github.com/openssh/openssh-portable
git://git.ghostscript.com/testcluster.git
git://git.ghostscript.com/mupdf-winrt.git
git://git.ghostscript.com/mupdf-ios-viewer.git
git://git.ghostscript.com/mupdf-ios-sdk.git
git://git.ghostscript.com/mupdf-android-viewer-mini.git
http://git.ghostscript.com/ghostpdl.git
git://git.ghostscript.com/ghostpdl.git
https://github.com/rrthomas/psutils

git://sourceware.org/git/bzip2.git
https://git.tukaani.org/xz.git

https://github.com/kivy/buildozer
https://github.com/kivy/kivy
https://github.com/google/flatbuffers
https://github.com/obsproject/obs-studio
https://github.com/jp9000/obs-studio
https://github.com/jp9000/obs

https://github.com/mkeeter/pont
https://github.com/nhn/tui.editor
https://github.com/JoeyDeVries/LearnOpenGL

https://github.com/libguestfs/libguestfs
https://github.com/libguestfs/supermin
https://github.com/libguestfs/nbdkit
https://github.com/libguestfs/libnbd
https://github.com/libguestfs/hivex
https://repo.or.cz/tinycc.git
https://github.com/vectorclass/version2
https://github.com/vectorclass/manual
https://github.com/vectorclass/testbench
https://github.com/vectorclass/miscellaneous
https://github.com/vectorclass/add-on
https://github.com/engineer-man/youtube

git://code.qt.io/qt/qt5.git
git://gcc.gnu.org/git/gcc.git
git://git.code.sf.net/p/zsh/code
git://git.ghostscript.com/mujs.git
git://git.ghostscript.com/mupdf-android-fitz.git
git://git.ghostscript.com/mupdf-android-viewer.git
git://git.ghostscript.com/mupdf.git
git://git.musl-libc.org/musl
git://git.openssl.org/openssl.git
git://git.sv.gnu.org/guile.git
https://crosstool-ng.github.io/
https://git.code.sf.net/p/freediag/gitrepo freediag-gitrepo
https://github.com/0xfe/vexchords
https://github.com/3dgen/cppwasm-book
https://github.com/acornjs/acorn
https://github.com/adafruit/Adafruit-GFX-Library
https://github.com/adamrenklint/bap
https://github.com/aguinet/dragonffi
https://github.com/alsa-project/alsa-utils
https://github.com/AltraMayor/f3
https://github.com/amber-smalltalk/amber
https://github.com/amber-smalltalk/amber-documentation
https://github.com/amber-smalltalk/amber-examples
https://github.com/amber-smalltalk/helios
https://github.com/andreasfertig/cppinsights
https://github.com/anoniscoding/yorlang/
https://github.com/ansible/ansible
https://github.com/ansilove/ansilove
https://github.com/antirez/redis
https://github.com/apple/cups
https://github.com/Apress/pro-android-python-w-sl4a
https://github.com/Apress/web-applications-with-elm
https://github.com/atom/teletype-client.git
https://github.com/atom/teletype-crdt.git
https://github.com/atom/teletype.git
https://github.com/atom/teletype-server.git
https://github.com/babel/babel
https://github.com/babel/babel
https://github.com/basecamp/trix
https://github.com/bazelbuild/examples/
https://github.com/billchurch/WebSSH2
https://github.com/blueman-project/blueman
https://github.com/bpampuch/pdfmake.git
https://github.com/bradtraversy/projectmanager
https://github.com/capnramses/antons_opengl_tutorials_book
https://github.com/carp-lang/Carp
https://github.com/cesanta/elk
https://github.com/cesanta/frozen
https://github.com/cesanta/mjs
https://github.com/cesanta/mongoose
https://github.com/cesanta/mongoose-os
https://github.com/cesanta/mongoose-os-docs
https://github.com/cesanta/slre
https://github.com/cesanta/v7
https://github.com/chakaz/reflang
https://github.com/chriscourses/voyager
https://github.com/chriskohlhoff/asio.git 
https://github.com/Clozure/ccl
https://github.com/commonmark/cmark
https://github.com/commonmark/commonmark-spec
https://github.com/conan-io/conan
https://github.com/cotejp/webmidi
https://github.com/CppCon/CppCon2018
https://github.com/crosstool-ng/crosstool-ng
https://github.com/cs01/gdbgui
https://github.com/cs01/pygdbmi
https://github.com/cyrus-and/gdb-dashboard
https://github.com/d3/d3
https://github.com/damonkohler/sl4a
https://github.com/DanRuta/wasm-arrays
https://github.com/dataarts/webgl-globe
https://github.com/devongovett/pdfkit.git
https://github.com/dgibson/dtc
https://github.com/diveintomark/diveintopython3
https://github.com/dvidelabs/flatcc
https://github.com/dwyl/english-words.git
https://github.com/ecere/ecere-sdk
https://github.com/ELENA-LANG/elena-lang
https://github.com/emweb/wt
https://github.com/erincatto/Box2D

https://github.com/espressif/mbedtls
https://github.com/espressif/arduino-esp32
https://github.com/espressif/esp-adf-libs
https://github.com/espressif/esp-idf
https://github.com/espressif/esp-idf.git
https://github.com/espressif/esp-nimble
https://github.com/espressif/esptool

https://github.com/espruino/Espruino
https://github.com/estools/escodegen
https://github.com/estree/estree
https://github.com/eteran/cpp-utilities
https://github.com/eteran/edb-debugger
https://github.com/eteran/nedit-ng
https://github.com/eteran/os64
https://github.com/eteran/pretendo
https://github.com/eteran/zippypy
https://github.com/facebookexperimental/rome
https://github.com/facebook/react-native
https://github.com/facebook/zstd
https://github.com/fltk/fltk.git
https://github.com/foliojs/fontkit
https://github.com/foliojs/pdfkit
https://github.com/forest-lang/forest-compiler
https://github.com/freeotp/freeotp-android
https://github.com/fullstackio/30-days-of-vue
https://github.com/fuse-open/uno
https://github.com/ghaerr/microwindows
https://github.com/gist/sylt/NO_NO_
https://github.com/gittup/alsa-utils
https://github.com/glfw/gleq
https://github.com/glfw/glfw
https://github.com/gnea/grbl
https://github.com/gnea/grbl.wiki.git
https://github.com/godotengine/godot
https://github.com/goldfire/howler.js
https://github.com/google/oboe
https://github.com/google/tink
https://github.com/gps67/rant_o_matic_01a.git
https://github.com/gps67/YEAR_src_PLAY
https://github.com/gps67/YEAR_src_PLAY_PREP
https://github.com/gpujs/gpu.js
https://github.com/grbl/grbl
https://github.com/groeck/lm-sensors
https://github.com/hakimel/reveal.js
https://github.com/hakimel/zoom.js
https://github.com/hioa-cs/IncludeOS.git
https://github.com/Hopson97/MineCraft-One-Week-Challenge
https://github.com/iamshaunjp/vuejs-playlist
https://github.com/IanDarwin/Android-Cookbook-Examples
https://github.com/ianstormtaylor/permit
https://github.com/idea4good/GuiLite
https://github.com/idea4good/GuiLiteSamples
https://github.com/idea4good/GuiLiteToolkit
https://github.com/idea4good/meltdown
https://github.com/idea4good/mnist
https://github.com/idea4good/spectre
https://github.com/jamiebuilds/the-super-tiny-compiler
https://github.com/jedisct1/libsodium
https://github.com/Jermolene/TiddlyWiki5
https://github.com/jerryscript-project/jerryscript.git
https://github.com/JetBrains/ring-ui.git
https://github.com/jrfonseca/xdot.py
https://github.com/juj/emsdk.git
https://github.com/juj/emsdk.git
https://github.com/JuliaLang/julia
https://github.com/kindahl/infrarecorder WIN dvd burn optional mp3 plugin
https://github.com/koczkatamas/onelang
https://github.com/krig/LISP
https://github.com/kripken/emscripten
https://github.com/kti/python-netfilterqueue
https://github.com/kuri65536/python-for-android
https://github.com/kuri65536/sl4a
https://github.com/leaningtech/cheerp-meta
https://github.com/liballeg/allegro5
https://github.com/libcpu/libcpu
https://github.com/liberationfonts/liberation-fonts
https://github.com/libffi/libffi
https://github.com/libfuse/libfuse
https://github.com/libharu/libharu
https://github.com/libharu/libharu.wiki.git
https://github.com/lieff/minimp3
https://github.com/LilyGO/ESP32-TTGO-T1
https://github.com/LinuxCNC/linuxcnc.git
https://github.com/littlevgl/lvgl
https://github.com/lm-sensors/lm-sensors
https://github.com/luketeaford/TANGUY
https://github.com/lynnagara/draw-app
https://github.com/lz4/lz4
https://github.com/makepad/boiler
https://github.com/makepaddev/makepad
https://github.com/makepaddev/wpoc
https://github.com/makepad/jsast
https://github.com/makepad/makepad.github.io
https://github.com/mdn/browser-api-demo
https://github.com/mdn/css-examples
https://github.com/mdn/webassembly-examples
https://github.com/mdn/webassembly-examples/
https://github.com/mdn/webaudio-examples
https://github.com/mdn/webextensions-examples
https://github.com/mdn/webgl-examples
https://github.com/meenie/band.js/
https://github.com/meganz/android.git
https://github.com/meganz/MEGAsync
https://github.com/meganz/sdk
https://github.com/meganz/webclient
https://github.com/memononen/fontstash
https://github.com/memononen/nanosvg
https://github.com/memononen/nanovg
https://github.com/MidnightCommander/mc.git
https://github.com/Minds/nomad
https://github.com/mozilla-spidermonkey/mozilla-spidermonkey.github.io
https://github.com/mozilla-spidermonkey/spidermonkey-embedding-examples
https://github.com/spidermonkey-embedders/spidermonkey-embedding-examples
https://github.com/mrdoob/three.js
https://github.com/mxe/mxe.git
https://github.com/myliang/x-spreadsheet
https://github.com/neobrain/cftf
https://github.com/neonious/lowjs
https://github.com/nhnent/tui.calendar
https://github.com/nhnent/tui.chart
https://github.com/nhnent/tui.editor
https://github.com/nicolasgramlich/AndEngine
https://github.com/nicolasgramlich/AndEngineExamples
https://github.com/nicolasgramlich/AndEnginePhysicsBox2DExtension
https://github.com/nidud/asmc/
https://github.com/nigels-com/glew.git
https://github.com/nim-lang/Nim
https://github.com/nim-lang/nimble
https://github.com/nim-lang/packages
https://github.com/nim-lang/website
https://github.com/ninja-build/ninja.git
https://github.com/nkolban/duktape-esp32 JS
https://github.com/nkolban/esp32-snippets
https://github.com/notepad-plus-plus/notepad-plus-plus
https://github.com/nothings/stb
https://github.com/nothings/stb-imv
https://github.com/ocornut/imgui
https://github.com/OneLoneCoder/olcPixelGameEngine
https://github.com/OneLoneCoder/olcRealTimeSFX
https://github.com/OneLoneCoder/synth
https://github.com/OneLoneCoder/videos
https://github.com/openglredbook/examples
https://github.com/opengl-tutorials/ogl
https://github.com/OpenVPN/easy-rsa
https://github.com/OpenVPN/easy-rsa
https://github.com/OpenVPN/openvpn
https://github.com/OpenVPN/openvpn3
https://github.com/OpenVPN/openvpn3.git core
https://github.com/OpenVPN/openvpn3-linux
https://github.com/OpenVPN/tap-windows
https://github.com/pharo-project/pharo
https://github.com/pirple/C-Plus-Plus-For-the-Rest-Of-Us
https://github.com/pirple/Keeping-Up-With-the-Javascripts
https://github.com/pirple/Python-Is-Easy
https://github.com/pirple/The-NodeJS-Master-Class
https://github.com/pirple/The-NodeJS-Master-Class
https://github.com/preactjs/preact
#https://github.com/prosemirror
https://github.com/pshihn/rough
https://github.com/pshihn/workly
https://github.com/pyglet/pyglet
https://github.com/qpython-android/qpython
https://github.com/qutebrowser/qutebrowser.git
https://github.com/reactiveui/Akavache
https://github.com/recombinant/petzold-pw5e
https://github.com/redom/redom
https://github.com/ReturnInfinity/BareMetal-OS
https://github.com/rougier/freetype-gl
https://github.com/rust-lang/book
https://github.com/rust-lang/rust.git
https://github.com/rustwasm/wasm-bindgen
https://github.com/Samsung/iotjs
https://github.com/shooshx/zippypy
https://github.com/sindresorhus/got
https://github.com/skvadrik/re2c
https://github.com/sp4cerat/Game-GUI
https://github.com/spbooks/jsninja2
https://github.com/sphinx-doc/sphinx
https://github.com/StephenGrider/AdvancedReduxCode
https://github.com/StephenGrider/AdvancedReduxCode/tree/master
https://github.com/StephenGrider/ReduxSimpleStarter
https://github.com/studio/studio
https://github.com/svaarala/duktape
https://github.com/telmich/gpm.git
https://github.com/tensorflow/mlir
https://github.com/ternjs/acorn.git
https://github.com/TigerVNC/tigervnc
https://github.com/tmux/tmux
https://github.com/toml-lang/toml
https://github.com/toml-lang/toml.io
https://github.com/tree-sitter/node-tree-sitter
https://github.com/tree-sitter/py-tree-sitter
https://github.com/tree-sitter/tree-sitter
https://github.com/tree-sitter/tree-sitter-bash
https://github.com/tree-sitter/tree-sitter-c
https://github.com/tree-sitter/tree-sitter-cpp
https://github.com/tree-sitter/tree-sitter-css
https://github.com/tree-sitter/tree-sitter-embedded-template
https://github.com/tree-sitter/tree-sitter.github.io
https://github.com/tree-sitter/tree-sitter-html
https://github.com/tree-sitter/tree-sitter-java
https://github.com/tree-sitter/tree-sitter-javascript
https://github.com/tree-sitter/tree-sitter-json
https://github.com/tree-sitter/tree-sitter-python
https://github.com/tree-sitter/tree-sitter-regex
https://github.com/tree-sitter/tree-sitter-rust
https://github.com/turbo/js
https://github.com/TurboVNC/turbovnc
https://github.com/unicorn-engine/unicorn
https://github.com/vim/vim.git
https://github.com/VirtualGL/virtualgl
https://github.com/w3c/wasm-wg/
https://github.com/walmik/scribbletune.git
https://github.com/WebAssembly/binaryen
https://github.com/WebAssembly/proposals
https://github.com/WebAssembly/reference-types
https://github.com/WebAssembly/spec
https://github.com/WebAssembly/wabt
https://github.com/wesbos/es6.io.git
https://github.com/wesbos/JavaScript30.git
https://github.com/wesbos/Learn-Redux-Starter-Files.git
https://github.com/wesbos/React-For-Beginners-Starter-Files.git
https://github.com/wolfssl/wolfssl
https://github.com/x64dbg/capstone_wrapper
https://github.com/x64dbg/x64dbg
https://github.com/x64dbg/x64dbg
https://github.com/x64dbg/x64dbg
https://github.com/ziglang/zig
https://github.com/zmartzone/mod_auth_openidc
https://gitlab.com/ReturnInfinity/BareMetal-OS.git
https://gitlab.com/zsaleeba/fpython.git
https://gitlab.com/zsaleeba/persist.git
https://gitlab.com/zsaleeba/picoc.git
https://gitlab.freedesktop.org/libevdev/libevdev.git
https://gitlab.freedesktop.org/libinput/libinput
https://gitlab.freedesktop.org/mesa/demos.git
https://gitlab.freedesktop.org/mesa/mesa.git

https://gitlab.kitware.com/cmake/cmake
https://git.netfilter.org/libnetfilter_queue/
https://git.savannah.gnu.org/cgit/freetype/freetype2.git/NO
https://git.savannah.gnu.org/git/groff.git
https://git.zx2c4.com/WireGuard
https://resources.oreilly.com/examples/9781565922921.git
https://resources.oreilly.com/examples/9781565925670.git
https://sourceware.org/git/insight.git
#http://www.passportjs.org/docs/username-password/
https://github.com/mdn/translated-content

git://thekelleys.org.uk/dnsmasq.git
#https://github.com/dlang/dmd.git
#https://github.com/vuejs/vue.git
#https://gitlab.com/konradp/tinydrum.git
#https://github.com/idea4good/lvgl
#https://github.com/rg3/youtube-dl
http://github.com/FreeRTOS/FreeRTOS
https://github.com/FreeRTOS/FreeRTOS-Kernel
#https://github.com/ribomation/DroidAtScreen1
https://github.com/pjps/ndjbdns/
https://LIST_END.com/OVER/DONE

"
for U in $L1
do
	GET_GIT $U
done

# NO # https://gankro.github.io/blah/rust-layouts-and-abis/
# NO https://github.com/bazelbuild/bazel/
