#!/bin/sh

. ./.env
#mysql_root <<!EOT
mysql_user <<!EOT

USE $BASE_NAME;

CREATE TABLE line_id (
	id	int(8) NOT NULL auto_increment,
	linetype ENUM( 'series', 'point_time', 'point_date' ) NOT NULL,
	site	varchar(20) NOT NULL,
	host	varchar(11) NOT NULL,
	dev	varchar(11) NOT NULL,
	cmd	varchar(11) NOT NULL,
	opt	varchar(11) NOT NULL,
	attr	varchar(11) NOT NULL,
	dt	int         NOT NULL,
	avg	varchar(11) NOT NULL,

	descr	varchar(20) DEFAULT '',

	PRIMARY KEY (site,host,dev,cmd,opt,attr,dt,avg),
	KEY byid (id)
);

CREATE TABLE seg (
	line	int(8) NOT NULL,
	t0	int(8) NOT NULL,
	t2	int(8) NOT NULL,
	data	BLOB,
	PRIMARY KEY (line,t0)
);

