#!/bin/sh

. ./.env
# why is user not allowed ...
# alter table requires select, insert, delete, update, create and drop privileges on the table. 
mysql_root <<!EOT

USE $BASE_NAME;

ALTER TABLE line_id ADD linetype ENUM( 'series', 'point_date', 'point_time' ) NOT NULL AFTER id;

# key does NOT use linetype

# ALTER TABLE line_id DROP PRIMARY KEY;

# ALTER TABLE line_id ADD PRIMARY KEY
# (site,host,dev,cmd,opt,attr,dt,avg);


